(defun make-sqr (rad col)
  (list (make-tri (list (list 0 0 0)
			(list rad 0 0)
			(list rad rad 0)) col)
	(make-tri (list (list 0 0 0)
			(list 0 rad 0)
			(list rad rad 0)) col)
	(make-tri (list (list 0 0 rad)
			(list rad 0 rad)
			(list rad rad rad)) col)
	(make-tri (list (list 0 0 rad)
			(list 0 rad rad)
			(list rad rad rad)) col)
	(make-tri (list (list 0 0 0)
			(list 0 0 rad)
			(list 0 rad rad)) col)
	(make-tri (list (list 0 0 0)
			(list 0 rad 0)
			(list 0 rad rad)) col)
	(make-tri (list (list rad 0 0)
			(list rad 0 rad)
			(list rad rad rad)) col)
	(make-tri (list (list rad 0 0)
			(list rad rad 0)
			(list rad rad rad)) col)))

